//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.08 at 04:31:39 AM WAT
//
package com.hextremelabs.ussd.ui.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="option" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="trigger" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="nextScreen" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="footer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://dev.hextremelabs.net}screenType" />
 *       &lt;attribute name="validation" type="{http://dev.hextremelabs.net}validation" />
 *       &lt;attribute name="regex" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="callback" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nextScreen" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
  "header",
  "option",
  "body",
  "footer"
})
public class Screen {

  @XmlElement(required = true)
  protected String header;
  protected List<Option> option;
  protected String body;
  protected String footer;
  @XmlAttribute(name = "id", required = true)
  protected String id;
  @XmlAttribute(name = "type", required = true)
  protected ScreenType type;
  @XmlAttribute(name = "validation")
  protected Validation validation;
  @XmlAttribute(name = "regex")
  protected String regex;
  @XmlAttribute(name = "callback")
  protected String callback;
  @XmlAttribute(name = "nextScreen")
  protected String nextScreen;

  /**
   * Gets the value of the header property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getHeader() {
    return header;
  }

  /**
   * Sets the value of the header property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setHeader(String value) {
    this.header = value;
  }

  /**
   * Gets the value of the option property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the option property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getOption().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Option }
   *
   *
   */
  public List<Option> getOption() {
    if (option == null) {
      option = new ArrayList<Option>();
    }
    return this.option;
  }

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getBody() {
    return body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setBody(String value) {
    this.body = value;
  }

  /**
   * Gets the value of the footer property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFooter() {
    return footer;
  }

  /**
   * Sets the value of the footer property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFooter(String value) {
    this.footer = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link ScreenType }
   *
   */
  public ScreenType getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link ScreenType }
   *
   */
  public void setType(ScreenType value) {
    this.type = value;
  }

  /**
   * Gets the value of the validation property.
   *
   * @return possible object is {@link Validation }
   *
   */
  public Validation getValidation() {
    return validation;
  }

  /**
   * Sets the value of the validation property.
   *
   * @param value allowed object is {@link Validation }
   *
   */
  public void setValidation(Validation value) {
    this.validation = value;
  }

  /**
   * Gets the value of the regex property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getRegex() {
    return regex;
  }

  /**
   * Sets the value of the regex property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setRegex(String value) {
    this.regex = value;
  }

  /**
   * Gets the value of the callback property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getCallback() {
    return callback;
  }

  /**
   * Sets the value of the callback property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setCallback(String value) {
    this.callback = value;
  }

  /**
   * Gets the value of the nextScreen property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getNextScreen() {
    return nextScreen;
  }

  /**
   * Sets the value of the nextScreen property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setNextScreen(String value) {
    this.nextScreen = value;
  }

}
