//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.08 at 04:31:39 AM WAT
//
package com.hextremelabs.ussd.lib.ui.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="trigger" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="nextScreen" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
  "value"
})
public class Option {

  @XmlValue
  protected String value;
  @XmlAttribute(name = "trigger", required = true)
  protected byte trigger;
  @XmlAttribute(name = "nextScreen", required = true)
  protected String nextScreen;

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the trigger property.
   *
   */
  public byte getTrigger() {
    return trigger;
  }

  /**
   * Sets the value of the trigger property.
   *
   */
  public void setTrigger(byte value) {
    this.trigger = value;
  }

  /**
   * Gets the value of the nextScreen property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getNextScreen() {
    return nextScreen;
  }

  /**
   * Sets the value of the nextScreen property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setNextScreen(String value) {
    this.nextScreen = value;
  }

}
