//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.07 at 03:20:54 PM WAT
//
package com.hextremelabs.ussd.lib.ui.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for screenType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="screenType"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration
 * value="options"/> &lt;enumeration value="textInput"/> &lt;enumeration value="display"/> &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "screenType")
@XmlEnum
public enum ScreenType {

  @XmlEnumValue("options")
  OPTIONS("options"),
  @XmlEnumValue("textInput")
  TEXT_INPUT("textInput"),
  @XmlEnumValue("display")
  DISPLAY("display");
  private final String value;

  ScreenType(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ScreenType fromValue(String v) {
    for (ScreenType c : ScreenType.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
